### PR TITLE
CI: Comparing test results with golden files

### PR DESCRIPTION
**Pull request by mdeweerd**
I've added golden files to the test setup.

The generated xlsx files are converted to CSV files which are then compared to the golden files.

This will allow the detection of changes in the future.

An error is generated if this fails.

(Hopefully) works with travis.

### CODE REVIEW

**Comment by hildogjr** [comment]
Are you planing to create some automatic CI to compare the XLXS results at any pull request file changes?

**Comment by mdeweerd** [comment]
Yes, this is the purpose - it seems to work - Py3.7 passed now after removing some files that should not have been there.
I compare CSV files created from the XLSX files.

**Comment by mdeweerd** [comment]
https://travis-ci.com/github/xesscorp/KiCost/jobs/339512671 fails because there is a different result than with the other python versions.  So this probably reveils some kind of bug.

**Comment by mdeweerd** [comment]
I consider that the tests are now effective and capable of identifying bugs and changes (the golden files may need to be updated of course after making a functional change - just copy the "result_test" directory to the "expected_test" directory if needed.

test_small.sh woks with "result_test_small" and "expected_test_small" .

**Comment by hildogjr** [comment]
Can I merge it now?

**Comment by mdeweerd** [comment]
Sometimes it is a matter of order (in the references field) - to be fixed by ordering the values in this field.

But there are also more profound differences:
> "C1,C2",000004V1RA,CAP CER 27PF 50V NP0 0402,_*000004V1RA*_,Kemet,C0402C270J5GACTU,0,0,0

> "C1,C2",000004V1RA,CAP CER 27PF 50V NP0 0402,_*CAP CER 27PF 50V NP0 0402*_,Kemet,C0402C270J5GACTU,0,0,0

with `diff -r result_test/TestParts.csv expected_test/TestParts.csv` on `Python 3.5.6`

**Comment by mdeweerd** [comment]
You can merge it ;-)

**Pull request merged**
