### PR TITLE
Add support for distributor TME (Issue #76)

### PR DESCRIPTION
**Pull request by adamheinrich**
This PR implements #76. Contrary to other distributor implementations, the code has to do additional XmlHTTPRequests to obtain pricing information and stock availability (because the website is not loaded as a single HTML page).

This implementation does up to four HTTP requests per part. A modified implementation could reduce this to two requests ([explained](https://github.com/adamheinrich/KiCost/blob/distributor-tme/kicost/tme/tme.py#L242) in a TODO comment). Is it OK to postpone this optimization to the future?

### CODE REVIEW

**Comment by hildogjr** [comment]
I add you file in a new branch that I am creating `https://github.com/hildogjr/KiCost/tree/restructuration` (missing add in the documentation).
I intend to deal with #34 and improve the reliability of the code. I would like that you test (uncomment the line 38 in the file `distributors_definitions.py` in the folder `distributors`. In my connection, sometimes the TME got timeout.

**Comment by adamheinrich** [comment]
Hi @hildogjr,
> I add you file in a new branch that I am creating

Why?

> In my connection, sometimes the TME got timeout.

I'll try to test it with some VPN. Maybe it will be enough to increase the number of attempts (`HTML_RESPONSE_RETRIES`). Where are you from?

**Comment by hildogjr** [comment]
A just tried to add because one of the proposed modification in my new branch is that the user do not need to modify the main `kicost.py` code to add new distributors or cad software. I think this would make more easy the community to add new modules (you do not need to understand) and maintenance (some people have this two different focus: software/kicad module and internet/distributor).

Also, I do not add the documentation to keep you request merge to main branch and authorship of the file when I request my merge.

I am from Brazil, now it is working. I will try to modify the `number of attempts` in the next time of time out, thanks by the tip.

**Comment by adamheinrich** [comment]
I've just updated the commit so that it is no longer in conflict with the recent changes in master.

**Comment by adamheinrich** [comment]
Hi @hildogjr,
> A just tried to add because one of the proposed modification in my new branch is that the user do not need to modify the main kicost.py code to add new distributors or cad software.

I think that's wrong. The standard approach is IMHO to add the support for TME in one PR and to do your refactoring in another PR (without the new file `tme.py`; I'm OK with updating it according to the new structure if the refactoring PR gets merged first).

Also, the commit history is a bit convoluted -- commit named "[Files restruturation (issue #77)](https://github.com/hildogjr/KiCost/commit/d88fdb83108bd3e586efa0d9857ff1eb5862f35f)" adds file `tme.py` (which is a new feature rather than change of the file structure).

Could you please revert it? I think it's enough to remove `tme.py` from d88fdb83108bd3e586efa0d9857ff1eb5862f35f and to remove commit 1c3607056f78f97262246ed01175be763c132004.

**Comment by adamheinrich** [comment]
I've just updated the commit again to be in sync with the last changes in the structure.

**Comment by xesscorp** [comment]
Adam, I merged your module into the master branch. It looks like getting part info out of TME is very complicated. Thanks for doing that! I added you to the list of authors.

I did correct a small error that appeared when running KiCost under Python 3.5: I had to decode the response from the TME URL request into a string, otherwise `json.loads()` would choke on it.

**Comment by adamheinrich** [comment]
Hi @xesscorp, thank you and sorry for the error.

**Comment by xesscorp** [comment]
No problem, Adam. I do the same thing all the time. Thanks for the TME scraper!

**Comment by hildogjr** [comment]
Now that we are adding new distributors. We may add some control when call `kicost` able or disable some distributors and the number of retry.
We could add `--retry [n]` to modify `HTML_RESPONSE_RETRIES` and `--distributors` to just use the distributors that we want to scrap.
What do you think?

**Comment by adamheinrich** [comment]
>  --distributors to just use the distributors that we want to scrap

The `--include` option does exactly what you want.

**Comment by hildogjr** [comment]
True, I read now.

**Pull request merged**
