### PR TITLE
Support for RS Components, Farnell and Altium Designer

### PR DESCRIPTION
**Pull request by glcerone**
I have added support for RS Components and Farnell suppliers.
With the --altium option it is possible to use kicost also with xml BOM files generated with Altium Desginer (e.g. using kicost -i myfile.xml --altium).

### CODE REVIEW

**Comment by xesscorp** [comment]
Hey, thanks for the updates!

There are some issues:
1. The modified kicost hangs on some of my test XML files. In particular, it gets to the 99% complete on RPI-test.xml and then just runs forever with no progress. (I just added the test XML files to the repo so you could get them.)
2. The Farnell and RS Component web sites provide prices in currencies other than US dollars. This screws-up the lowest-cost price selection in the spreadsheet. Either the prices need to be converted to dollars or some way needs to be found to make all the scraped websites use the same currency.

**Comment by glcerone** [comment]
Hi xesscorp,

thanks for appreciating my updates.

1) I ran kicost for the RPI-test.xml file on my PC and it correctly works without looping forever. I tested the script on Windows 10 + Python 3.5.2 and Ubuntu Linux + Python 2.7.12 without differences. The command i used (i suppose that is the same of you) is "kicost -i RPI-test.xml". I attach the result file RPI-test.xlsx

[RPi-Test.xlsx](https://github.com/xesscorp/KiCost/files/521146/RPi-Test.xlsx)

2) The Farnell and RS Component web sites provide prices in Euro. This is a problem. I can resolve this problem converting the currency in US dollar taking dinamically the conversion value (e.g. from Google). This solution is convenient to add (in future) an option to the xlsx file that enable the user to use the preferred currency. Let me know if you agree with this option.

Thanks,
GL Cerone

**Comment by glcerone** [comment]
I fixed the currencies problem with RS Components and Farnell as described in the previous post.

**Comment by MickMad** [comment]
I tested it on some BOMs and it works properly. I think this is a good addition to KiCost.

**Comment by xesscorp** [comment]
The pull request has been integrated into the master branch along with some other changes. Thanks!

**Pull request merged**
