### PR TITLE
Multipart components (issue #34) & Spreadsheetorder (issue #84)

### PR DESCRIPTION
**Pull request by hildogjr**
Improved by the issue #84: spreadsheet order groups fixed
Multipart components issue #34 ready to use
`altium` module moved to `eda_tools` folders to group the routines and configurations (issue #84 not already implemented in altium module)

### CODE REVIEW

**Comment by hildogjr** [comment]
@xesscorp, you can remove the merge request #82, already merged in my main branch.
An maybe the #62 of your list.

**Comment by hildogjr** [comment]
@xesscorp , read to test and merge.
Missing: multipart (issue #34) affect in altium BOM, this need some deep analyze of `altium.py` (I don't have a ALtium XML to test here).
But the order (iussue #84) already affect altium and kicad BOMs.
It was made some minor improvements and corrections.

**Comment by xesscorp** [comment]
I merged your previous PR on 9/23/2017. Here are the changes I made:

1) Created a kicad subdirectory under eda_tools.
2) Moved get_part_groups() from kicost.py to eda_tools/kicad/kicad.py.
3) Changed -a option to --eda_tools option that lets you specify kicad or altium as the EDA tool.
4) Fixed collapse_refs() to handle part reference ids with subparts.
5) Removed group_sort() and replaced it with a plain alphabetical sort of part reference ids.
6) Moved part ref id sorting into add_globals_to_worksheet() after collapse_refs() is called so sorting is correct.
7) Cleaned-up eda_tools.py  bit.

**Comment by hildogjr** [comment]
Nice, I am grateful that my code and ideas is representing  some improvement.

Just the sub part sorted order that are not really good. I got a `J1#3,J1#2,J1#1` and `U4#3,U4#2,U4#4,U4#1`, nothing is missing, it is just not in the alphabetic order.

Other think that we have to keep in mind is that, when we use different connector in the board, e.g. Molex
https://www.digikey.com/products/en?WT.z_header=search_go&lang=en&keywords=0022232051%20
https://www.digikey.com/products/en?WT.z_header=search_go&lang=en&keywords=0022012057%20
https://www.digikey.com/products/en?WT.z_header=search_go&lang=en&keywords=08-50-0114%20

the contact part `08-50-0114` may be used in more than one connector (of different number of vias) reflecting in a group with `Refs` like `J1#3,J3#2`, I predict this idea by the use of  `CEILING` to subpart component. But we have to be sure that this grouping is possible in `kicost` (may create different rows in the spreadsheet because  `kicost` do not group components of different libraries / footprints).

**Comment by hildogjr** [comment]
@xesscorp, I fixed the documentation because of the extinct comand `--altium`.

**Comment by xesscorp** [comment]
I'm getting an error with your PR because the groups_sort() isn't defined anywhere. I noticed you put that in at the top of the create_spreadsheet() function. Did you do that because you are trying to do some sorting on the subparts? If so, I think I can add that to the sorting I'm doing down in the add_globals_to_worksheet() function. Let me know if there's any other reasons for doing that.

I'm thinking of doing a new release with all the new features. I'll probably get around to that on Sunday morning. Do you want the option for increasing the number of HTTP retries?

**Comment by hildogjr** [comment]
I merged if the your main and delete this function from the `eda_tools.py` (returned now but not actived). This function put the order that I wanted the refs in the spreadsheet (usually U first and R and C at the last).

Yes, one external option to HTTP retries will be nice.

**Comment by hildogjr** [comment]
Other think, I was not able to modify `altium.py` to add sub parts because the struct of execution is quite different of `kicad.py` `get_parts()`.

**Pull request merged**
