### PR TITLE
User experience optimazation

### PR DESCRIPTION
**Pull request by hildogjr**
Now:
1) Count the parts founded in each distributors;
2) Count the parts purchased in each distributors;
Missing: add some logic to not count `0` quantity. Also eliminate `0, PART` of the purchase code list.
3) Put yellow background in the general Qty if the user forgot to order sufficient quantity of one part.

### CODE REVIEW

**Comment by hildogjr** [comment]
Added some logic to control user erros like forgot to buy some part or enough quantity.

**Comment by hildogjr** [comment]
One correction to the `pull request`
"Missing: add some logic to not count `0` quantity"
means
Add logic to not count parts that is not present in the distributor (seeing the presence of column `Unit$`), even if the use of the spreadsheet put a `Purch` quantity.

**Comment by hildogjr** [comment]
This propose (for the issues #7 and other user improvements) is finished.
Please, check if is something userful (this is in the older standard of files, but all changes is in `kicost.py`).
Now, I am working on #34 with other branch.

**Comment by hildogjr** [comment]
@xesscorp the issues of this request is due the new file hierarchy implemented.
Please check only the modification in the `kicost.py` file. The others was not modified.

**Comment by xesscorp** [comment]
I'm going through this and reviewing the changes to kicost.py.

**Comment by hildogjr** [comment]
Let me know if I can help with the review, and this ideas that I propose are really useful.

**Comment by xesscorp** [comment]
I merged your changes into master. I made some alterations:

1) The `Qty` column now shows status using three colors:
    a) Red if the total quantity available for all distributors is zero.
    b) Orange if the total quantity available is non-zero but less than the quantity needed.
    c) Yellow if the total quantity is sufficient, but the quantity ordered is less.
2) The `manf#` column is no longer used to indicate the availability of a part.
3) The `Avail` column for each distributor now shows status using two colors:
    a) Red if the quantity available at the distributor is zero.
    b) Orange if the quantity available is non-zero but less than the quantity needed.
4) The `Purchased` column for each distributor now shows status using one color:
    a) Red if the quantity to be purchased is greater than the available quantity from the distributor.

**Comment by xesscorp** [comment]
hildogjr, your ideas have been very useful for improving the user interface. I had to go through them and alter some of your ideas, but I would never have done this if you had not thought of these features and done an initial implementation.

**Pull request merged**
