### PR TITLE
Fix #370 - Variant handling for "kicost.<variant>:field" fixed

### LINKED ISSUE #370: kicost.VARIANT:manf# field doesn't work
The documentation says:

> KiCost supports another way of specifying the variant associated with a part. Using the example from above, labeling the part number for J1 as kicost.v1:manf# will assign it to the v1 variant. This method is not as flexible as using the variant field and ** may be removed in future versions of KiCost **.

I think it has to be maintained as this seems to be the only way to select different components according to the variant.
The "modern variant" field only allows to specify if the component is present or not in the BOM.

The Old style variant specification allows to select one type of connector in one case, an another type in another case, a smaller fuse in one case or a bigger one, different resistor values according to the variant, etc.

So it seems best to maintain it, update the documentation and add a reminder in the source code -).

### PR DESCRIPTION
**Pull request by mdeweerd**
Fix for #370

### CODE REVIEW

**Comment by hildogjr** [comment]
`('manf#', 'manf', 'desc', 'value', 'comment', 'S1PN', 'S1MN', 'S1PL', 'S2PN', 'S2MN', 'S2PL')` is an specific case yours, it not possible to merge this code. The `('manf#', 'manf', 'desc', 'value')` is correct, but the other field should be taken by some internal definition/variables.

**Comment by hildogjr** [comment]
Close due not fix in general use.

**Comment by mdeweerd** [comment]
It's a pity that all code changes are thrown away this way - it suffices to ignore the change on line 100 (in the new version).

**Comment by hildogjr** [comment]
Doing it the variant problem is fixed?

**Comment by mdeweerd** [comment]
Yes, the variant problem is fixed by applying the variant regex independently on the variant part itself (and not "integrated" in the total regex where "^" and "$" of the variant regex no longer apply).

Regarding the limitation to "('manf#', 'manf', 'desc', 'value')" only, I am not sure that this test makes sense here - at leaste the way it is used anyway.

The code first tests to see if there is a "variant" expression using a regex like `'kicost(\.(?P<variant>.*))?:(?P<name>.*)'`

This can match `kicost.<variant>:comment` for instance, but also `kicost:comment` .

If the field is defined to be variant dependent, then it should override the normal field if the variant is matched.

The test `name not in ('manf#', 'manf') and name[:-1] not in distributor_dict` supposes that `name[:-1]` is a distributor, but there is no test that the last character of "name" is actually a '#' token which is the designated way to indicate that this modifier is for a distributor.  The test for '#' as the last character of "name" should be added, and the only exception would be "manf#" in that case.

**Comment by johnthagen** [comment]
FYI, CI failures are fixed in #379

**Pull request closed without merging**
